### PR TITLE
Responsive Navbar Added

### PR DESCRIPTION
**Pull request by hamzailyas237**
I have added a responsive navbar to your project. I have used a little bit of javascript to toggle the navbar.
Thank you.

### CODE REVIEW

**Comment by hamzailyas237** [comment]
Did you add hactoberfest label?

**Comment by hamzailyas237** [comment]
Please add hactoberfest label so that it counts in hactoberfest PR

**Comment by iamneeraj542** [comment]
added

**Comment by iamneeraj542** [comment]
what problem are you facing write it down here ??

**Pull request merged**
